### ISSUE TITLE
What's the Chat ID

### ISSUE THREAD

**Issue by hmnd** [drtomasso/osticket-telegram#1]
What do I put for Chat ID in the config?

**Comment by foamrider** [comment]
After you've created a bot (using Bot Father, see: https://core.telegram.org/bots), add the bot to a group or `/start` a chat with your bot. You can then read the chat ID opening: `https://api.telegram.org/bot<token>/getUpdates`
Example: `https://api.telegram.org/bot123456:ABC-DEF1234ghIkl-zyx57W2v1u123ew11/getUpdates`

The bot token is generated and displayed by the Bot Father when creating a bot, this is a secret key.
