### ISSUE TITLE
More data and update in message

### ISSUE THREAD

**Issue by mcphisto1979** [drtomasso/osticket-telegram#3]
Hi,
I'm a very beginner with PHP code. Just wanted to ask, if and how I can modify your wonderful plugin, to receive the message even when a ticket is modified or updated.
Is there a way to receive even phone number and the text of the ticket in notification message?

Thank you.

**Comment by foamrider** [comment]
Unfortunately adding a hook for update/modify event is limited by osTicket. Until they implement a better API, it only works on ticket creation.

For adding more details from a ticket, you can experiment with `$ticket-getBody()` and `$ticket-getPhoneNumber()` (haven't tested these). Such functions isn't documented either.

**Comment by mcphisto1979** [comment]
Hi,
thank you. Already tried with getPhoneNumber(), no errors, but I don't get phone number in telegram. With getBody(), I get a 500 error after opening the ticket.
