### ISSUE TITLE
problem email's

### ISSUE THREAD

**Issue by cagami** [drtomasso/osticket-telegram#4]
hi
Problems in the emails in which there is a _
If the address has _ then the notification will not come
Example cagami_online@live.com

**Comment by cagami** [comment]
`				"text" => "<b>New Ticket:</b><a href=\"".$ticketLink."\">#".$ticketId."</a>\n<b>Subject:</b>".$title."\n<b>Created by:</b> ".$createdBy,
				"parse_mode" => "html",
`

**Comment by cagami** [comment]
the whole problem is due to the markup, if _ is encountered, then the telegram is waiting for the italic font

**Comment by foamrider** [comment]
I've added it to the code, thank you
