### ISSUE TITLE
Add body message

### ISSUE THREAD

**Issue by leksakov** [drtomasso/osticket-telegram#5]
Hi!
That's great plugin!
I have one question. Is it possible to add to notifications text of the ticket?
I was looking for something like that getBody, getMessage, but did not work.
This is a very useful function.

**Comment by foamrider** [comment]
Seems like it might be something like this:

Inside `onTicketCreated` function:
```php
$body = $ticket->getLastMessage()->getMessage() ?: 'No content';
```

**Comment by leksakov** [comment]
Yeah, it works!

But if ticket send via e-mail (html), noitifcation in telegram looks like that:
![2017-12-06 16 53 37](https://user-images.githubusercontent.com/19302062/33664837-0caa495e-daa6-11e7-96cf-e28cf61b7a56.png)

Send via e-mail (text) likes good.

That sound crazy, Is it possible for the marking of the html to be filtered out ?

**Comment by foamrider** [comment]
Yes, use PHP function `strip_tags` (http://php.net/manual/en/function.strip-tags.php)

Maybe like this:
```php
$body = $ticket->getLastMessage()->getMessage() ?: 'No content';
$body = strip_tags($body);
```

**Comment by leksakov** [comment]
Great! Thank you!
