### ISSUE TITLE
notifications from email tickets don't work

### ISSUE THREAD

**Issue by spitfireska88** [drtomasso/osticket-telegram#7]
drtomasso, hi! Thx for the plugin. It works fine, but when tickets are opened through web interface of osticket. 
In situation when clients open tickets via email -  I don't recieve notifications. Is it right?

**Comment by foamrider** [comment]
It should notify when created via both email and web. Do you have the "include body" on? Have you tried with it off?

**Comment by spitfireska88** [comment]
Yeah,  "include body" was on. Then I tried to switch off "include body". But the situation didn't change. Through the web interface - I have notifications, via email - I don't.

**Comment by spitfireska88** [comment]
Maybe reason is in the version of Osticket?  What version do you use? Mine is v1.10

**Comment by Pietro-Aretino** [comment]
Hey there, I have your plugin installed but am getting the following error:
Error posting to Telegram. https://api.telegram.org/bot1234567:ABCDEFGEIvMHp-3JuLIVJqLizalYJPLvW8wk Http code: 502, referer: http://10.10.10.10/scp/tickets.php?a=open&uid=3

**Comment by foamrider** [comment]
@spitfireska88 I used v1.10, but has moved on to another ticketing system. Therefore I am unable to do further testing.

@Pietro-Aretino Could be a missing trailing `/` in your URL
